name: Rust-Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    types: [ opened, synchronize, reopened ]

jobs:
  Rust-Tests:
    name: Rust-Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
    
    - name: Run tests
      run: cargo test --verbose
